### ISSUE TITLE
add avatar component

### ISSUE THREAD

**Issue by radnan** [optimizely-axiom/optiaxiom#48]

**Comment by radnan** [comment]
@mostafa-K-raihan please fill out the description with a summary of the api you're going forward with

**Comment by mostafa-K-raihan** [comment]
I cannot update the description of the issue here. but here is what I am planning to do -
- I will be using the radix primitives underneath. https://www.radix-ui.com/primitives/docs/components/avatar
For now, the avatar component will take these props as optional
```
- src: string
- alt: string
- colorScheme: axiom color
- size: xl, lg, md, sm, xs
- name: string
- icon: React.ReactNode
- children: React.ReactNode
```
- The `src` has a higher priority.
- If `icon` is provided and `src` is not, then we will render the icon instead.
- If no `src`/`icon` is provided or `src` is provided but the component fails to load the `src` URL, then the `children` will be rendered. Ideally, 
- The `children` will be a couple of letters indicating the user's initials, but we can pass anything, like count `(+2)`. If no `children` are provided, it will try to use the `name` prop and extract the initials. If nothing is provided, we should render a default/static `user` icon.
- The `icon` will be rendered, if no `src` is provided.
- The `colorScheme` will be used to override the default color of the avatar.
- The `size` prop will dictate how big/small will be the component.
